# Filename can be whatever you want, however config.yaml is loaded by default.

# Standard variable example.
username: "HEROLAB_USERNAME"
password: "HERLAB_PASSWORD"

# Dictionary variable example.
stuff_and_things:
  stuff: "thing"
  things: "stuff"

# Dictionary to list variable example.
stuff:
  - "thing1"
  - "thing2"

