# DO NOT ADJUST ANYTHING IN THIS FILE UNLESS DIRECTED TO DO SO.
# THIS FILE IS NOT EMBEDDED INTO THE EXECUTABLE TO MAKE ANY REQUIRED ADJUSTMENTS EASIER 
# SHOULD THE PIXELS DEVELOPERS CHANGE ANYTHING THAT COULD AFFECT THESE VALUES.

# HEX values of die results.
DIE_RESULTS:
  "16000a": Stopped rolling.
  "030113": 20
  "030112": 19
  "030111": 18
  "030110": 17
  "03010f": 16
  "03010e": 15
  "03010d": 14
  "03010c": 13
  "03010b": 12
  "03010a": 11
  "030109": 10
  "030108": 9
  "030107": 8
  "030106": 7
  "030105": 6
  "030104": 5
  "030103": 4
  "030102": 3
  "030101": 2
  "030100": 1

# THIS IS ONLY HERE FOR MY REFERENCE
# bytearray(b'\x02\x14     \x04      \x07w\x88\xce     \x94"p\xde9\x98\x1e\xf7\     xdd\x01f\x01\x13K     \x02')
#                  die_size\die_color                  pixel_id                                   battery_%
#                  [1]      [2]                        [8-12]reversed                             [20]

